steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--build-arg=GIT_SHA=${GIT_SHA}'
  - '-t'
  - '${REGION}-docker.pkg.dev/$PROJECT_ID/${REPOSITORY}/${IMAGE_NAME}:${GIT_SHA}'
  - '.'
images:
- '${REGION}-docker.pkg.dev/$PROJECT_ID/${REPOSITORY}/${IMAGE_NAME}:${GIT_SHA}'

# LOCATION AND PROJECT_ID ARE DEFINED BY GCLOUD BUILD BY DEFAULT REMOVE {}