name: Promote Code to production
on:
    pull_request:
        branches: [main]
        types: [closed] 
permissions:
    contents: 'read'
    id-token: 'write'
env:
    SERVICE_ACCOUNT: 'vertexai-runner@companytesting-480806.iam.gserviceaccount.com'
    WIF_PROVIDER: 'projects/558007337566/locations/global/workloadIdentityPools/github-pool/providers/my-repo'
    IMAGE_NAME: 'torch-train'
    PROJECT_ID: 'companytesting-480806'
    REGION: 'us-central1'
    ARTIFACT_REPO_NAME: 'train-dev-containers'
    DEFAULT_CONTAINER_URL: 'docker.pkg.dev'
    PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
jobs:
    promote-code:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: GCloud Login
              uses: ./.github/actions/auth
              with:
                service_account: ${{ env.SERVICE_ACCOUNT }}
                wif_provider: ${{ env.WIF_PROVIDER }}
            - name: set up gcloud
              uses: google-github-actions/setup-gcloud@v3
            - name: add latest tag
              run: |
               gcloud artifacts docker tags add \
                ${{ env.REGION }}-${{ env.DEFAULT_CONTAINER_URL }}/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.PR_HEAD_SHA }} \
                ${{ env.REGION }}-${{ env.DEFAULT_CONTAINER_URL }}/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
            - name: Echo sha commit
              run: echo "PR_HEAD_SHA=${PR_HEAD_SHA}"