name: Test Pytorch Code
on:
    pull_request:
        branches:
            - main
env:
    SERVICE_ACCOUNT: 'vertexai-runner@companytesting-480806.iam.gserviceaccount.com'
    WIF_PROVIDER: 'projects/558007337566/locations/global/workloadIdentityPools/github-pool/providers/my-repo'
    IMAGE_NAME: 'torch-train'
    PROJECT_ID: 'companytesting-480806'
    REGION: 'us-central1'
    ARTIFACT_REPO_NAME: 'train-dev-containers'
    DEFAULT_CONTAINER_URL: 'docker.pkg.dev'
    GITHUB_SHA: ${{ github.sha }}
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
          contents: 'read'
          id-token: 'write'
        steps:
            - name: check out code
              uses: actions/checkout@v7
            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v3
              with:
                    token_format: 'access_token'
                    workload_identity_provider: ${{ env.WIF_PROVIDER }}
                    service_account: ${{ env.SERVICE_ACCOUNT }}
            
            - name: set up gcloud
              uses: google-github-actions/setup-gcloud@v3

            - name: Submit to gcloud build
              run: |
                gcloud builds submit train_component \
                --tag ${{ env.REGION }}-${{ env.DEFAULT_CONTAINER_URL }}/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            
            - name: install python dependencies
              run: pip install google-cloud-aiplatform --break-system-packages
            - name: set status as pending
              run: |
                curl -X POST \
                  -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github+json" \
                  https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                  - d '{
                    "state": "pending",
                    "context": "vertex-test/pipeline-status",
                    "description": "Wait for pipeline to finish"
                  }'
            - name: Trigger Vertex AI pipeline
              run: python3 pipeline_runner.py